------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

---

### 0. Importar librerías.

In [11]:
# Importamos la librería numpy con alias np
import numpy as np

### 1. Crea un vector entre 7 y 66.


In [12]:
# creamos el vector
vector = np.linspace(7, 66, num = 60)
print(type(vector))
print(vector.dtype)
print(vector)

<class 'numpy.ndarray'>
float64
[ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.
 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42.
 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60.
 61. 62. 63. 64. 65. 66.]


---

### 2. Invierte el vector generado anteriormente.

In [13]:
# Opción A para invertir un vector
inv_vector = vector[::-1]
print(inv_vector)

# Opción B para invertir un vector
inv_vector = np.flip(vector)
print(inv_vector)

[66. 65. 64. 63. 62. 61. 60. 59. 58. 57. 56. 55. 54. 53. 52. 51. 50. 49.
 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32. 31.
 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14. 13.
 12. 11. 10.  9.  8.  7.]
[66. 65. 64. 63. 62. 61. 60. 59. 58. 57. 56. 55. 54. 53. 52. 51. 50. 49.
 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32. 31.
 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14. 13.
 12. 11. 10.  9.  8.  7.]


---

### 3. Matriz de 4x4 con valores entre 0 y 15.


In [21]:
# Creación de una matriz de 4x4 con valores entre 0 y 15

matriz = [
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]]
print(matriz)

matriz = np.empty((4,4))
print(matriz.shape)

matriz = np.arange(4 * 4).reshape(4, 4)
print(matriz)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### 4. Crea la matriz identidad de 5x5.


In [22]:
matriz = np.identity(5).astype(int)
print(matriz)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### 5. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.

In [28]:
matriz = np.identity(5).astype(int)
matriz[2,:]  = 1
matriz[:,2]  = 1
matriz[0,:]  = 1
matriz[-1,:] = 1
matriz[:,0]  = 1
matriz[:,-1] = 1
print(matriz)

[[1 1 1 1 1]
 [1 1 1 0 1]
 [1 1 1 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]]


In [34]:
# Creamos la matriz de 5x5 llena de ceros con .zeros()
matriz = np.zeros((5,5))

# Asignamos el valor 1 a la posición central.
matriz[2,2]  = 1

# Asignamos el valor 1 a la posición que conforman el marco.
matriz[0,:]  = 1
matriz[-1,:] = 1
matriz[:,0]  = 1
matriz[:,-1] = 1

print(matriz)

[[ 1  1  1  1  1]
 [ 1  0  0  0  1]
 [ 1  0  1  0  1]
 [ 1  0  0  0  1]
 [ 1  1  1  1  1]]


### 6. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.


In [41]:
matriz = np.zeros((4,4), dtype = int)

for i in range(4):
    matriz[i] = np.arange(3, -1, -1)

print(matriz)

[[3 2 1 0]
 [3 2 1 0]
 [3 2 1 0]
 [3 2 1 0]]


### 7. Crea un array de ceros de 2x7.

In [42]:
matriz = np.zeros((2,7))
print(matriz)

[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]


### 8. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.

In [62]:
# Opción A

matriz = np.zeros((5, 4))

matriz[0,:2] = 1
print(matriz)

# Opción B

m = np.vstack([np.ones((1,4)), np.zeros((4,4))])
print(m)

[[ 1  1  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
[[ 1  1  1  1]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


### 9. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0

In [67]:
# Vamos a crear un tablero de ajedrez 
# Array de 8x8
# 0 = cuadrado blanco
# 1 = cuadrado negro

# Creamos una matriz de ceros, es decir todos los cuadrados son blancos (0)
matriz = np.zeros((8,8))

# Cremos los cuadrados negros (1)
matriz[1::2, ::2] = 1
matriz[::2, 1::2] = 1

# Imprimimos la tabla de ajedrez
print(matriz)

[[ 0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0]
 [ 0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0]
 [ 0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0]
 [ 0  1  0  1  0  1  0  1]
 [ 1  0  1  0  1  0  1  0]]
